### ISSUE TITLE
Problem in compiling payloads

### ISSUE THREAD

**Issue by shawshank666** [PSPReverse/amd-sp-glitch#1]
I'm reproducing your work and have a problem when compiling the makefile of payloads. I use Ubuntu(21.04) `arm-none-eabi-*` toolchain. After running `make` an error is reported:
>arm-none-eabi-gcc -Os -I../include -I../Lib/include -std=gnu99 -fomit-frame-pointer -nostartfiles -ffreestanding -Wextra -Werror -c -o _start.o _start.S
make: arm-none-eabi-gcc: No such file or directory

I don't know the relative path of your payloads file and can't find where `../include` and `../Lib/include` are. Could you specify the path of these files? Looking forward to your reply.

**Comment by hnj2** [comment]
Thanks for your interest in our work!

The message:
> make: arm-none-eabi-gcc: No such file or directory

means that arm-none-eabi-gcc could not be found (it's not in the PATH).
You can verify that this is the issue by running the comman: `arm-none-eabi-gcc --version`

To fix this issue you can either install the required package `sudo apt install gcc-arm-none-eabi` or if you already have an arm-none-eabi toolchain installed add it to the PATH like so: `PATH="${PATH}:/path/to/toolchain/bin"`

**Comment by hnj2** [comment]
I think the issue is resolved :)

**Comment by shawshank666** [comment]
Thanks for your reply! I have already solved this problem. Actually the PATH is correctly added. However, `arm-none-eabi-gcc` is a 32-bit executable file so it can not run in 64-bit Ubuntu. I installed the relevant dependency `lib32z1` and run `make` successfully.
